version: '3'
services:
  database:
    image: postgres:latest
    #build: .
    env_file:
      - .env
    ports:
      - "5432:5432"
      - "15432:15432"
      #volumes:
      #- ./data/db:/var/lib/postgresql/data
      #- ./conf/:/var/lib/postgresql/data/
